from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from app.core.config import get_settings

settings = get_settings()


def send_fraud_alert_email(
    transaction_id: str,
    amount: float,
    merchant: str,
    location: str,
    card_last4: str,
    fraud_score: float,
    risk_level: str
) -> bool:
    """
    Send fraud alert email via SendGrid.
    Returns True if email sent successfully, False otherwise.
    """

    # Risk level color
    color_map = {
        "CRITICAL": "#FF0000",
        "HIGH":     "#FF6600",
        "MEDIUM":   "#FFA500",
        "LOW":      "#FFD700",
        "SAFE":     "#00CC00"
    }
    color = color_map.get(risk_level, "#FF0000")

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; background: #f4f4f4; margin: 0; padding: 0; }}
            .container {{ max-width: 600px; margin: 30px auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }}
            .header {{ background: #0f172a; padding: 30px; text-align: center; }}
            .header h1 {{ color: white; margin: 0; font-size: 24px; }}
            .header p {{ color: #94a3b8; margin: 5px 0 0; }}
            .alert-badge {{ background: {color}; color: white; text-align: center; padding: 15px; font-size: 20px; font-weight: bold; letter-spacing: 2px; }}
            .body {{ padding: 30px; }}
            .detail-row {{ display: flex; justify-content: space-between; padding: 12px 0; border-bottom: 1px solid #f1f5f9; }}
            .detail-label {{ color: #64748b; font-size: 14px; }}
            .detail-value {{ color: #0f172a; font-weight: 600; font-size: 14px; }}
            .score-box {{ background: #fef2f2; border: 2px solid {color}; border-radius: 8px; padding: 20px; text-align: center; margin: 20px 0; }}
            .score-number {{ font-size: 48px; font-weight: bold; color: {color}; }}
            .score-label {{ color: #64748b; font-size: 14px; margin-top: 5px; }}
            .footer {{ background: #f8fafc; padding: 20px; text-align: center; color: #94a3b8; font-size: 12px; }}
            .action-btn {{ display: inline-block; background: #3b82f6; color: white; padding: 12px 30px; border-radius: 8px; text-decoration: none; font-weight: 600; margin-top: 15px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🛡️ FinSentinel</h1>
                <p>AI-Powered Fraud Detection System</p>
            </div>
            <div class="alert-badge">
                ⚠️ FRAUD ALERT — {risk_level} RISK
            </div>
            <div class="body">
                <p style="color:#64748b; font-size:14px;">A suspicious transaction has been detected. Please review immediately.</p>

                <div class="score-box">
                    <div class="score-number">{fraud_score}%</div>
                    <div class="score-label">Fraud Probability Score</div>
                </div>

                <div class="detail-row">
                    <span class="detail-label">Transaction ID</span>
                    <span class="detail-value">{transaction_id[:8].upper()}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Amount</span>
                    <span class="detail-value">${amount:,.2f}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Merchant</span>
                    <span class="detail-value">{merchant}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Location</span>
                    <span class="detail-value">{location}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Card</span>
                    <span class="detail-value">**** **** **** {card_last4}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Risk Level</span>
                    <span class="detail-value" style="color:{color};">{risk_level}</span>
                </div>

                <p style="margin-top:20px; color:#64748b; font-size:13px;">
                    This alert was automatically generated by FinSentinel AI. 
                    Please investigate this transaction immediately.
                </p>
            </div>
            <div class="footer">
                <p>FinSentinel — AI Fraud Detection System</p>
                <p>This is an automated alert. Do not reply to this email.</p>
            </div>
        </div>
    </body>
    </html>
    """

    message = Mail(
        from_email=settings.ALERT_FROM_EMAIL,
        to_emails=settings.ALERT_TO_EMAIL,
        subject=f"🚨 FinSentinel Alert — {risk_level} Risk Transaction Detected (${amount:,.2f})",
        html_content=html_content
    )

    try:
        sg = SendGridAPIClient(settings.SENDGRID_API_KEY)
        response = sg.send(message)
        print(f"Alert email sent — Status: {response.status_code}")
        return True
    except Exception as e:
        print(f"Failed to send alert email: {e}")
        return False